name: Deploy Monorepo

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'ref to build'
        required: true
      path:
        description: 'path'
      public-url:
        description: 'public url for build'
      build-flags:
        description: 'additional build flags'
      env:
        description: 'set env for build'
      patch-workers:
        description: 'if workers should be patched'
        type: boolean
      repository:
        description: 'repository for genshin-optimizer'
        default: eeeqeee/genshin-optimizer

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout genshin-optimizer
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.repository }}
        ref: ${{ github.event.inputs.ref }}
        path: genshin-optimizer
        ssh-key: ${{ secrets.ssh_key_optimizer }}
    - name: Disable files
      run: |
        echo > genshin-optimizer/libs/dm/scripts/loadDM.ts
    - name: Checkout GenshinData
      uses: actions/checkout@v3
      with:
        repository: eeeqeee/GenshinData
        ref: trimmed
        path: genshin-optimizer/libs/dm/GenshinData
        ssh-key: ${{ secrets.ssh_key_genshindata }}
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
        cache-dependency-path: genshin-optimizer/yarn.lock
    - name: Get path
      id: get-path
      run: |
        if [[ -z "${{ github.event.inputs.path }}" ]]; then
          echo "path=/genshin-optimizer/$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        else
          echo "path=${{ github.event.inputs.path }}" >> $GITHUB_OUTPUT
        fi
      working-directory: genshin-optimizer
    - name: Get public url
      id: get-public-url
      run: |
        if [[ -z "${{ github.event.inputs.public-url }}" ]]; then
          # N.B. can't use "." since workers will resolve relative to their own path e.g "static/js/static/js/..."
          echo "url=${{ steps.get-path.outputs.path }}/" >> $GITHUB_OUTPUT
        else
          echo "url=${{ github.event.inputs.public-url }}" >> $GITHUB_OUTPUT
        fi
      working-directory: genshin-optimizer
    - name: Get commit msg
      id: get-commit-msg
      run: |
        echo "msg=\"deploy: $(git rev-parse HEAD) to ${{ steps.get-path.outputs.path }}\"" >> $GITHUB_OUTPUT
      working-directory: genshin-optimizer
    - run: |
        yarn install --immutable --immutable-cache --check-cache
      working-directory: genshin-optimizer
    - name: Patch for worker bug
      if: github.event.inputs.patch-workers == 'true'
      run: |
        sed -i "s/scriptType: internalOptions.esm ? 'module' : undefined,/scriptType: 'text\/javascript',/" node_modules/@nrwl/webpack/src/utils/config.js
      working-directory: genshin-optimizer
    - name: Build genshin-optimizer
      run: |
        ${{ github.event.inputs.env }} yarn run buildall --base-href="${{ steps.get-public-url.outputs.url }}" ${{ github.event.inputs.build-flags }}
      working-directory: genshin-optimizer
    - name: Checkout gh-pages
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages
    - name: Move to gh-pages
      run: |
        mkdir --parents "gh-pages/${{ steps.get-path.outputs.path }}"
        rm -rfv "gh-pages/${{ steps.get-path.outputs.path }}" || true
        mv "genshin-optimizer/dist/apps/frontend" "gh-pages/${{ steps.get-path.outputs.path }}"
    - name: Make commit to deploy
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add ./"${{ steps.get-path.outputs.path }}"
        git commit -m ${{ steps.get-commit-msg.outputs.msg }}
        git push origin gh-pages
      working-directory: gh-pages
